'use client'

import React, { useState, useEffect } from 'react'
import { useRouter, useParams } from 'next/navigation'
import { AdminInput } from '@/components/Admin/AdminFormField'

// Helper function to generate URL-friendly slug from text
function generateSlug(text: string): string {
  return text
    .toLowerCase()
    .trim()
    .replace(/[^\w\s-]/g, '') // Remove special characters
    .replace(/[\s_-]+/g, '-') // Replace spaces and underscores with hyphens
    .replace(/^-+|-+$/g, '') // Remove leading/trailing hyphens
}

interface Tag {
  id: string
  name: string
  slug: string
  blogCount: number
  createdAt: string
  updatedAt: string
}

const EditTagPage = () => {
  const router = useRouter()
  const params = useParams()
  const id = params.id as string
  const [form, setForm] = useState<Tag | null>(null)
  const [customSlug, setCustomSlug] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [loading, setLoading] = useState(false)
  const [fetching, setFetching] = useState(true)

  useEffect(() => {
    loadTag()
  }, [id])

  const loadTag = async () => {
    try {
      const res = await fetch(`/api/tags/${id}`, { cache: 'no-store' })
      if (res.ok) {
        const data = await res.json()
        setForm(data)
      } else {
        setError('Tag not found')
      }
    } catch (error) {
      console.error('Error loading tag:', error)
      setError('Failed to load tag')
    } finally {
      setFetching(false)
    }
  }

  const handleNameChange = (name: string) => {
    if (form) {
      setForm({
        ...form,
        name,
        slug: customSlug ? form.slug : generateSlug(name),
      })
    }
  }

  const handleSlugChange = (slug: string) => {
    if (form) {
      setForm({ ...form, slug })
      setCustomSlug(true)
    }
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    if (!form) return

    setError(null)
    setLoading(true)

    try {
      const payload = {
        name: form.name.trim(),
        slug: customSlug ? form.slug.trim() : undefined, // Let server regenerate if not custom
      }

      const res = await fetch(`/api/tags/${id}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload),
      })

      if (res.ok) {
        router.push('/admin/tags')
      } else {
        const json = await res.json()
        setError(json.error || 'Failed to update tag')
      }
    } catch (error) {
      console.error('Error updating tag:', error)
      setError('Failed to update tag')
    } finally {
      setLoading(false)
    }
  }

  if (fetching) {
    return <div className="text-secondary">Loading...</div>
  }

  if (!form) {
    return <div className="text-red">Tag not found</div>
  }

  const autoGeneratedSlug = generateSlug(form.name)

  return (
    <div className="max-w-2xl">
      <h1 className="heading4 mb-6">Edit Tag</h1>
      <form onSubmit={handleSubmit} className="space-y-4">
        <AdminInput
          label="Name"
          type="text"
          required
          value={form.name}
          onChange={(e) => handleNameChange(e.target.value)}
          placeholder="Enter tag name"
        />

        <div className="space-y-1">
          <label className="text-title">
            Slug {!customSlug && <span className="text-secondary text-sm">(auto-generated)</span>}
          </label>
          <input
            type="text"
            value={form.slug}
            onChange={(e) => handleSlugChange(e.target.value)}
            className="w-full border border-line rounded px-3 py-2"
            placeholder="Enter slug"
          />
          {!customSlug && (
            <p className="text-sm text-secondary">
              Auto-generated from name. Click to edit manually.
            </p>
          )}
          {customSlug && autoGeneratedSlug !== form.slug && (
            <p className="text-sm text-yellow">
              Note: Slug differs from auto-generated value ({autoGeneratedSlug})
            </p>
          )}
        </div>

        <div className="space-y-1">
          <label className="text-title">Blog Count</label>
          <input
            type="text"
            value={form.blogCount}
            readOnly
            className="w-full border border-line rounded px-3 py-2 bg-surface text-secondary"
          />
          <p className="text-sm text-secondary">
            Number of blogs using this tag. Tag cannot be deleted if count is greater than 0.
          </p>
        </div>

        {error && <div className="text-red text-sm">{error}</div>}

        <div className="flex gap-4">
          <button
            type="button"
            onClick={() => router.back()}
            className="px-4 py-2 border border-line rounded-lg text-title hover:bg-surface"
          >
            Cancel
          </button>
          <button type="submit" disabled={loading} className="button-main">
            {loading ? 'Updating...' : 'Update Tag'}
          </button>
        </div>
      </form>
    </div>
  )
}

export default EditTagPage

