/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'contact-submissions': ContactSubmission;
    'product-collections': ProductCollection;
    products: Product;
    'product-variants': ProductVariant;
    'product-reviews': ProductReview;
    stores: Store;
    services: Service;
    pages: Page;
    posts: Post;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    'product-collections': ProductCollectionsSelect<false> | ProductCollectionsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    'product-variants': ProductVariantsSelect<false> | ProductVariantsSelect<true>;
    'product-reviews': ProductReviewsSelect<false> | ProductReviewsSelect<true>;
    stores: StoresSelect<false> | StoresSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    homepage: Homepage;
    'store-locator-settings': StoreLocatorSetting;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    'store-locator-settings': StoreLocatorSettingsSelect<false> | StoreLocatorSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Inbound contact form submissions from the storefront.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  name: string;
  email: string;
  message: string;
  honeypotTriggered?: boolean | null;
  /**
   * SHA-256 hash of requester IP (never store raw IP).
   */
  ipHash?: string | null;
  userAgent?: string | null;
  submissionStatus: 'new' | 'in_progress' | 'resolved' | 'spam';
  handledBy?: (number | null) | User;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-collections".
 */
export interface ProductCollection {
  id: number;
  title: string;
  slug: string;
  description?: string | null;
  /**
   * Lower numbers appear first in listings.
   */
  displayOrder?: number | null;
  featured?: boolean | null;
  coverImage?: (number | null) | Media;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  /**
   * High-level product line for storefront navigation and filtering.
   */
  productType: 'optical-frame' | 'sunglasses' | 'contact-soft' | 'contact-care' | 'accessory';
  name: string;
  slug: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Brand label shown on PDP and used in filtering.
   */
  brand?: string | null;
  /**
   * Optional GTIN/EAN/UPC for retail/integrations.
   */
  gtin?: string | null;
  /**
   * Display price (Phase 1 catalog only; no checkout).
   */
  price: number;
  /**
   * Catalog availability filter value for storefront search.
   */
  availabilityStatus: 'in-stock' | 'available';
  images?: (number | Media)[] | null;
  /**
   * Editorial groupings (multi-select). Used for /collections pages and collection filters.
   */
  collections?: (number | ProductCollection)[] | null;
  /**
   * Merchandising flag (e.g. homepage rows).
   */
  featured?: boolean | null;
  /**
   * Optional list of badge strings, e.g. ["new","bestseller"]. Kept as JSON to avoid extra join tables in Phase 1.
   */
  badges?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  frame?: {
    frameShape?: ('round' | 'rectangle' | 'square' | 'aviator' | 'cat-eye' | 'browline' | 'other') | null;
    rimType?: ('full-rim' | 'semi-rimless' | 'rimless' | 'other') | null;
    frameColor?: string | null;
    rxAble?: boolean | null;
    lensColor?: string | null;
    polarized?: boolean | null;
    uv400?: boolean | null;
    lensCategory?: number | null;
  };
  specs?: {
    /**
     * When off, the storefront hides the specs module.
     */
    showSpecsOnPdp?: boolean | null;
    /**
     * Bridge width (mm)
     */
    bridgeMm?: number | null;
    /**
     * Temple length (mm)
     */
    templeMm?: number | null;
    lensWidthMm?: number | null;
    lensHeightMm?: number | null;
    lensType?: ('single-vision' | 'progressive' | 'photochromic' | 'polarized' | 'other') | null;
    lensMaterial?: ('cr39' | 'polycarbonate' | 'high-index' | 'other') | null;
    lensTreatment?: ('anti-reflective' | 'blue-light' | 'uv' | 'scratch-resistant' | 'none') | null;
    frameMaterial?: ('acetate' | 'metal' | 'titanium' | 'mixed' | 'other') | null;
    /**
     * Short notes on fit (e.g. narrow bridge).
     */
    fitNotes?: string | null;
    /**
     * e.g. oval, heart — avoid color-only cues.
     */
    faceShapeHints?: string | null;
    dimensionDiagram?: (number | null) | Media;
  };
  contactLens?: {
    replacementSchedule?: ('daily' | 'biweekly' | 'monthly' | 'other') | null;
    unitsPerBox?: number | null;
    /**
     * JSON array of numbers, e.g. [8.4, 8.8]
     */
    baseCurveOptionsMm?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * JSON array of numbers, e.g. [14.0, 14.2]
     */
    diameterOptionsMm?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    spherePowerRange?: {
      min?: number | null;
      max?: number | null;
      step?: number | null;
    };
    hasCylinder?: boolean | null;
    cylinderPowerRange?: {
      min?: number | null;
      max?: number | null;
      step?: number | null;
    };
    axisStep?: number | null;
    hasAdd?: boolean | null;
    addPowerRange?: {
      min?: number | null;
      max?: number | null;
      step?: number | null;
    };
    materialType?: ('hydrogel' | 'silicone-hydrogel' | 'other') | null;
    waterContentPercent?: number | null;
    /**
     * Oxygen transmissibility (Dk/t), if known.
     */
    dkT?: number | null;
    wearingModality?: ('daily-wear' | 'extended-wear') | null;
  };
  careProduct?: {
    unitOfMeasure?: ('bottle' | 'box' | 'pack' | 'other') | null;
    unitVolumeMl?: number | null;
    unitsPerPack?: number | null;
    compatibility?: ('all' | 'soft-only' | 'other') | null;
  };
  accessory?: {
    accessoryType?: ('case' | 'cloth' | 'chain' | 'kit' | 'other') | null;
    unitsPerPack?: number | null;
    compatibilityNotes?: string | null;
  };
  /**
   * YouTube or Vimeo page URL (no autoplay on storefront).
   */
  videoUrl?: string | null;
  videoPoster?: (number | null) | Media;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-variants".
 */
export interface ProductVariant {
  id: number;
  product: number | Product;
  /**
   * e.g. Matte Black / 52-18-145
   */
  title: string;
  /**
   * Optional internal SKU for this specific variant.
   */
  sku?: string | null;
  /**
   * Optional GTIN/EAN/UPC for this variant.
   */
  gtin?: string | null;
  /**
   * Variant-specific images (falls back to product images if empty).
   */
  images?: (number | Media)[] | null;
  attributes?: {
    colorName?: string | null;
    colorCode?: string | null;
    lensWidthMm?: number | null;
    bridgeMm?: number | null;
    templeMm?: number | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-reviews".
 */
export interface ProductReview {
  id: number;
  product: number | Product;
  rating: number;
  title: string;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  authorName: string;
  verified?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stores".
 */
export interface Store {
  id: number;
  name: string;
  slug: string;
  address: string;
  city?: string | null;
  /**
   * Optional region or province for filtering.
   */
  region?: string | null;
  /**
   * E.164 or local format as you prefer.
   */
  phone?: string | null;
  /**
   * Full WhatsApp link, e.g. https://wa.me/6281234567890
   */
  whatsApp?: string | null;
  email?: string | null;
  /**
   * Google Maps (or other) URL for directions.
   */
  mapsUrl?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  hours?:
    | {
        day: 'mon' | 'tue' | 'wed' | 'thu' | 'fri' | 'sat' | 'sun';
        /**
         * e.g. 09:00
         */
        open?: string | null;
        /**
         * e.g. 21:00
         */
        close?: string | null;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  icon?: (number | null) | Media;
  displayOrder?: number | null;
  category: 'core_service' | 'premium_benefit';
  serviceType: 'exam' | 'fitting' | 'adjustments' | 'guarantee' | 'trade-in' | 'benefit' | 'other';
  /**
   * Optional Cal.com, Google Appointments, or other booking link.
   */
  bookingUrl?: string | null;
  /**
   * Optional phone for booking when no URL is set.
   */
  bookingPhone?: string | null;
  primaryCtaLabel?: string | null;
  /**
   * Large background image for the detail page hero section.
   */
  heroImage?: (number | null) | Media;
  /**
   * Main body content for the service detail page.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  processSteps?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  blocks?:
    | (
        | {
            body: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'content';
          }
        | {
            heading: string;
            subheading?: string | null;
            image?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            label: string;
            href: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            /**
             * Optional section title above the questions.
             */
            heading?: string | null;
            items?:
              | {
                  question: string;
                  answer: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  excerpt: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  featuredImage?: (number | null) | Media;
  category?: string | null;
  authorName: string;
  authorBio?: string | null;
  authorAvatar?: (number | null) | Media;
  /**
   * Example: 3 min read
   */
  timeToRead?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null)
    | ({
        relationTo: 'product-collections';
        value: number | ProductCollection;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'product-variants';
        value: number | ProductVariant;
      } | null)
    | ({
        relationTo: 'product-reviews';
        value: number | ProductReview;
      } | null)
    | ({
        relationTo: 'stores';
        value: number | Store;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  message?: T;
  honeypotTriggered?: T;
  ipHash?: T;
  userAgent?: T;
  submissionStatus?: T;
  handledBy?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-collections_select".
 */
export interface ProductCollectionsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  displayOrder?: T;
  featured?: T;
  coverImage?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  productType?: T;
  name?: T;
  slug?: T;
  description?: T;
  brand?: T;
  gtin?: T;
  price?: T;
  availabilityStatus?: T;
  images?: T;
  collections?: T;
  featured?: T;
  badges?: T;
  frame?:
    | T
    | {
        frameShape?: T;
        rimType?: T;
        frameColor?: T;
        rxAble?: T;
        lensColor?: T;
        polarized?: T;
        uv400?: T;
        lensCategory?: T;
      };
  specs?:
    | T
    | {
        showSpecsOnPdp?: T;
        bridgeMm?: T;
        templeMm?: T;
        lensWidthMm?: T;
        lensHeightMm?: T;
        lensType?: T;
        lensMaterial?: T;
        lensTreatment?: T;
        frameMaterial?: T;
        fitNotes?: T;
        faceShapeHints?: T;
        dimensionDiagram?: T;
      };
  contactLens?:
    | T
    | {
        replacementSchedule?: T;
        unitsPerBox?: T;
        baseCurveOptionsMm?: T;
        diameterOptionsMm?: T;
        spherePowerRange?:
          | T
          | {
              min?: T;
              max?: T;
              step?: T;
            };
        hasCylinder?: T;
        cylinderPowerRange?:
          | T
          | {
              min?: T;
              max?: T;
              step?: T;
            };
        axisStep?: T;
        hasAdd?: T;
        addPowerRange?:
          | T
          | {
              min?: T;
              max?: T;
              step?: T;
            };
        materialType?: T;
        waterContentPercent?: T;
        dkT?: T;
        wearingModality?: T;
      };
  careProduct?:
    | T
    | {
        unitOfMeasure?: T;
        unitVolumeMl?: T;
        unitsPerPack?: T;
        compatibility?: T;
      };
  accessory?:
    | T
    | {
        accessoryType?: T;
        unitsPerPack?: T;
        compatibilityNotes?: T;
      };
  videoUrl?: T;
  videoPoster?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-variants_select".
 */
export interface ProductVariantsSelect<T extends boolean = true> {
  product?: T;
  title?: T;
  sku?: T;
  gtin?: T;
  images?: T;
  attributes?:
    | T
    | {
        colorName?: T;
        colorCode?: T;
        lensWidthMm?: T;
        bridgeMm?: T;
        templeMm?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-reviews_select".
 */
export interface ProductReviewsSelect<T extends boolean = true> {
  product?: T;
  rating?: T;
  title?: T;
  body?: T;
  authorName?: T;
  verified?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stores_select".
 */
export interface StoresSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  address?: T;
  city?: T;
  region?: T;
  phone?: T;
  whatsApp?: T;
  email?: T;
  mapsUrl?: T;
  latitude?: T;
  longitude?: T;
  hours?:
    | T
    | {
        day?: T;
        open?: T;
        close?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  icon?: T;
  displayOrder?: T;
  category?: T;
  serviceType?: T;
  bookingUrl?: T;
  bookingPhone?: T;
  primaryCtaLabel?: T;
  heroImage?: T;
  content?: T;
  processSteps?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  blocks?:
    | T
    | {
        content?:
          | T
          | {
              body?: T;
              id?: T;
              blockName?: T;
            };
        hero?:
          | T
          | {
              heading?: T;
              subheading?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  featuredImage?: T;
  category?: T;
  authorName?: T;
  authorBio?: T;
  authorAvatar?: T;
  timeToRead?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  modules?:
    | (
        | {
            eyebrow?: string | null;
            heading: string;
            subheading?: string | null;
            image?: (number | null) | Media;
            ctaLabel?: string | null;
            ctaHref?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heroModule';
          }
        | {
            heading: string;
            subHeading?: string | null;
            collections?: (number | ProductCollection)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'collectionSpotlight';
          }
        | {
            heading: string;
            subHeading?: string | null;
            products?: (number | Product)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'productRow';
          }
        | {
            heading: string;
            subHeading?: string | null;
            posts?: (number | Post)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'journalFeature';
          }
        | {
            heading: string;
            body?: string | null;
            backgroundImage?: (number | null) | Media;
            linkLabel?: string | null;
            linkHref?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'seasonalBanner';
          }
      )[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "store-locator-settings".
 */
export interface StoreLocatorSetting {
  id: number;
  enabled?: boolean | null;
  defaultCenterLat: number;
  defaultCenterLng: number;
  defaultZoom: number;
  selectedZoom: number;
  maxZoom: number;
  fitBoundsPadding: number;
  markerRadius: number;
  /**
   * Hex color for unselected markers, e.g. #1f2937
   */
  markerColor: string;
  /**
   * Hex color for selected marker, e.g. #2563eb
   */
  selectedMarkerColor: string;
  tileUrl: string;
  tileAttribution: string;
  scrollWheelZoom?: boolean | null;
  dragging?: boolean | null;
  touchZoom?: boolean | null;
  doubleClickZoom?: boolean | null;
  showZoomControl?: boolean | null;
  showPopupDirections?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  modules?:
    | T
    | {
        heroModule?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              subheading?: T;
              image?: T;
              ctaLabel?: T;
              ctaHref?: T;
              id?: T;
              blockName?: T;
            };
        collectionSpotlight?:
          | T
          | {
              heading?: T;
              subHeading?: T;
              collections?: T;
              id?: T;
              blockName?: T;
            };
        productRow?:
          | T
          | {
              heading?: T;
              subHeading?: T;
              products?: T;
              id?: T;
              blockName?: T;
            };
        journalFeature?:
          | T
          | {
              heading?: T;
              subHeading?: T;
              posts?: T;
              id?: T;
              blockName?: T;
            };
        seasonalBanner?:
          | T
          | {
              heading?: T;
              body?: T;
              backgroundImage?: T;
              linkLabel?: T;
              linkHref?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "store-locator-settings_select".
 */
export interface StoreLocatorSettingsSelect<T extends boolean = true> {
  enabled?: T;
  defaultCenterLat?: T;
  defaultCenterLng?: T;
  defaultZoom?: T;
  selectedZoom?: T;
  maxZoom?: T;
  fitBoundsPadding?: T;
  markerRadius?: T;
  markerColor?: T;
  selectedMarkerColor?: T;
  tileUrl?: T;
  tileAttribution?: T;
  scrollWheelZoom?: T;
  dragging?: T;
  touchZoom?: T;
  doubleClickZoom?: T;
  showZoomControl?: T;
  showPopupDirections?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}